name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10.0-alpha.1"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Type Checker (mypy)
        run: tox -e mypy
      - name: Lint Files (flake8)
        run: tox -e pep8
      - name: Run Tox
        run: tox -e py
